name: Build and deploy Node.js app to Azure Web App - photome-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'dev'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
        env:
          BLOB_CONNECTION_STRING: ${{ secrets.BLOB_CONNECTION_STRING }}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_PORT: ${{secrets.DB_PORT}}
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_NAME: ${{secrets.DB_NAME}}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_921FB74EC8D24E6D9368439A29FF9F16 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_289DEA7C081D4441A1F26A8C4D1ACC9A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F6309402388849E0A3A568C9DD0779EE }}

      - name: Set App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: 'photome-dev'
          app-settings-json: |
            [
              {
                "name": "BLOB_CONNECTION_STRING",
                "value": "${{ secrets.BLOB_CONNECTION_STRING }}",
                "slotSetting": false
              },
              {
                "name": "DB_HOST",
                "value": "${{ secrets.DB_HOST }}",
                "slotSetting": false
              },
              {
                "name": "DB_PORT",
                "value": "${{ secrets.DB_PORT }}",
                "slotSetting": false
              },
              {
                "name": "DB_PASSWORD",
                "value": "${{ secrets.DB_PASSWORD }}",
                "slotSetting": false
              },
              {
                "name": "DB_NAME",
                "value": "${{ secrets.DB_NAME }}",
                "slotSetting": false
              },
              {
                "name": "DB_USERNAME",
                "value": "${{ secrets.DB_USERNAME }}",
                "slotSetting": false
              }
            ]

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'photome-dev'
          slot-name: 'Production'
          package: .
