name: Build and deploy Node.js app to Azure Web App - photome-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev # Use dev environment for build phase
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
        env:
          # Access the environment secrets for build
          BLOB_CONNECTION_STRING: ${{ secrets.BLOB_CONNECTION_STRING }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}

      - name: Create .env file for runtime
        run: |
          echo "BLOB_CONNECTION_STRING=${{ secrets.BLOB_CONNECTION_STRING }}" > .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env

      - name: Verify .env file exists
        run: |
          ls -la .env
          echo "Contents of current directory:"
          ls -la

      - name: Zip artifact for deployment
        run: |
          # Ensure hidden files are included
          zip -r release.zip . -i "*" ".*"
          # Verify zip contents
          unzip -l release.zip | grep .env

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Production # Use Production environment for deploy phase
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Verify .env file exists after unzip
        run: |
          ls -la .env
          echo "Contents of current directory after unzip:"
          ls -la

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_921FB74EC8D24E6D9368439A29FF9F16 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_289DEA7C081D4441A1F26A8C4D1ACC9A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F6309402388849E0A3A568C9DD0779EE }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'photome-dev'
          slot-name: 'Production'
          package: .
